import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {dark} from '@clerk/themes';
import { ThemeProvider } from "@/components/theme-provider"
import { ClerkProvider } from "@clerk/nextjs";
import { Navbar } from "./(browse)/_components/navbar";
import Sidebar, { SidebarSkeleton } from "./(browse)/_components/sidebar";
import Container from "./(browse)/_components/container";
import { Suspense } from "react";
import {Toaster} from 'sonner';



const inter = Inter({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Nexora",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}
 >
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased`}
      >
        
        <ThemeProvider
            attribute="class"
            forcedTheme="system"
            storageKey="nexora-theme"
          >
            <Toaster theme="light" position="bottom-center"/>
        <Navbar/>
           <div className="flex h-full pt-20">
            <Suspense fallback={<SidebarSkeleton/>}>
            <Sidebar/>
            </Suspense>
            <Container>
                {children}
            </Container>
            
            </div>
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
