import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {dark} from '@clerk/themes';
import { ThemeProvider } from "@/components/theme-provider"
import { ClerkProvider, SignedIn, SignedOut, SignInButton, SignUpButton, UserButton } from "@clerk/nextjs";

const inter = Inter({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Nexora",
  description: "Generated by create next app",
};

/**
 * Root layout component that sets up global authentication, theming, and font styles for the application.
 *
 * Wraps all pages with Clerk authentication providers, applies a dark theme, and configures the Inter font. Displays a sign-in button when signed out and a user menu when signed in. All page content is rendered within this layout.
 *
 * @param children - The page content to render within the layout
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}
    afterSignInUrl="/"     // 👈 your desired post-login route
    afterSignUpUrl="/" >
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            forcedTheme="system"
            storageKey="nexora-theme"
          >
        <header className="flex justify-end items-center p-4 gap-4 h-16">
            <SignedOut>
              <SignInButton >
                <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign In
                </button>
              </SignInButton>
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
              {/* <SignUpButton>
                <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign Up
                </button>
              </SignUpButton> */}
          </header>
          
        {children}
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
